data_dir: hopper-random-v2
model:
  actuator_forces:
    activation_fn: tanh
    hidden_layers:
    - 32
    - 32
    init_value: 0.001
  control_dependent_noise: false
  coriolis_matrix:
    activation_fn: tanh
    hidden_layers:
    - 32
    - 32
    init_value: 0.01
  data_state_scaling: true
  diffusion_density_nn:
    density_nn:
      activation_fn: swish
      hidden_layers:
      - 32
      - 32
      init_value: 0.01
    indx_noise_in:
    - 0
    - 1
    - 5
    - 6
    - 7
    indx_noise_out:
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    scaler_nn:
      init_value: 0.01
      type: scaler
  gravity:
    activation_fn: tanh
    hidden_layers:
    - 32
    - 32
    init_value: 0.001
  horizon: 1
  n_u: 3
  n_x: 11
  n_y: 11
  noise_prior_params:
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  num_particles: 1
  num_substeps: 4
  residual_forces:
    activation_fn: tanh
    hidden_layers:
    - 64
    - 64
    init_value: 0.01
  sde_solver: simpletic_euler_maruyama
  state_scaling:
  - 1.3532897233963013
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 2.8590662479400635
  - 2.585909843444824
  - 8.406386375427246
  - 9.823725700378418
  - 10.0
  - 10.0
  stepsize: 0.008
output_file: hop_rand_v2_dsc0.1_simple
ratio_seed: 10
ratio_test: 0.1
remove_test_data: false
sde_loss:
  data_stepsize: 0.008
  default_weights: 1.0
  density_loss:
    ball_nsamples: 20
    ball_radius: 0.1
    learn_mucoeff:
      type: constant
    mu_coeff: 10.0
  discount_pred: 0.1
  horizon: 2
  num_particles: 1
  obs_weights:
  - 1.3532897233963013
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 2.8590662479400635
  - 2.585909843444824
  - 8.406386375427246
  - 9.823725700378418
  - 10.0
  - 10.0
  pen_data: 1.0
  pen_density_scvex: 1.0
  pen_grad_density: 0.01
  pen_mu_coeff: 100.0
  pen_mu_type: lin_inv
  pen_scvex_mult: 1.0
  pen_weights: 1.0e-10
  seed: 1
  special_parameters_pen:
    density: 0
    scaler: 0
  stepsize: 0.008
  warmup_diffusion: 10
sde_optimizer:
- name: scale_by_adam
- name: linear_schedule
  params:
    end_value: -0.001
    init_value: -0.01
    transition_steps: 40000
  scheduler: true
sde_training:
  TestStopingCrit:
    totalLoss: 1
  TrainStopingCrit:
    totalLoss: 0.1
  nepochs: 5000
  patience: 2000
  save_freq: 500
  test_batch: 512
  test_freq: 50
  train_batch: 128
