data_dir: hopper-medium-v2
model:
  actuator_forces:
    activation_fn: tanh
    hidden_layers:
    - 32
    - 32
  control_dependent_noise: false
  coriolis_matrix:
    activation_fn: tanh
    hidden_layers:
    - 32
    - 32
  data_state_scaling: true
  diffusion_density_nn:
    density_nn:
      activation_fn: swish
      hidden_layers:
      - 32
      - 32
      init_value: 0.01
    indx_noise_in:
    - 0
    - 1
    - 5
    - 6
    - 7
    indx_noise_out:
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    scaler_nn:
      init_value: 0.01
      type: scaler
  gravity:
    activation_fn: tanh
    hidden_layers:
    - 32
    - 32
  horizon: 1
  n_u: 3
  n_x: 11
  n_y: 11
  noise_prior_params:
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  num_particles: 1
  num_substeps: 4
  residual_forces:
    activation_fn: tanh
    hidden_layers:
    - 128
    - 128
  sde_solver: simpletic_euler_maruyama
  state_scaling:
  - 1.7290250062942505
  - 0.19498887658119202
  - 1.4930675029754639
  - 1.4813905954360962
  - 0.9639512300491333
  - 5.0179290771484375
  - 5.189232349395752
  - 3.8315834999084473
  - 6.485666751861572
  - 10.0
  - 10.0
  stepsize: 0.05
output_file: medium_hop_v13
ratio_seed: 10
ratio_test: 0.1
remove_test_data: true
sde_loss:
  data_stepsize: 0.008
  default_weights: 1.0
  density_loss:
    ball_nsamples: 20
    ball_radius: 0.1
    learn_mucoeff:
      type: constant
    mu_coeff: 10.0
  discount_pred: 0.1
  horizon: 5
  num_particles: 1
  obs_weights:
  - 1.7290250062942505
  - 0.19498887658119202
  - 1.4930675029754639
  - 1.4813905954360962
  - 0.9639512300491333
  - 5.0179290771484375
  - 5.189232349395752
  - 3.8315834999084473
  - 6.485666751861572
  - 10.0
  - 10.0
  pen_data: 100.0
  pen_density_scvex: 1.0
  pen_grad_density: 0.1
  pen_scvex_mult: 1.0
  pen_weights: 1.0e-10
  seed: 25
  special_parameters_pen:
    density: 0
    scaler: 0
  stepsize: 0.008
  warmup_diffusion: 30
sde_optimizer:
- name: scale_by_adam
- name: linear_schedule
  params:
    end_value: -0.0001
    init_value: -0.01
    transition_steps: 100000
  scheduler: true
sde_training:
  TestStopingCrit:
    totalLoss: 1
  TrainStopingCrit:
    LossUnc: 0.1
    totalLoss: 1.0
  nepochs: 300
  num_test_eval_per_epoch: 10
  patience: 30
  test_batch: 512
  train_batch: 128
