dad_optimizer:
- name: scale_by_adam
- name: linear_schedule
  params:
    end_value: -0.001
    init_value: -0.001
    transition_steps: 100000
  scheduler: true
dataset:
  name: halfcheetah-medium-expert-v2
  normalize_data: true
  seed: 10
  test_ratio: 0.2
env_name: halfcheetah-medium-expert-v2
extra_infos:
  is_diff_distance_aware: true
  max_fields:
    Abfoot: 5.1890549659729
    Abshin: 3.31099271774292
    Abthigh: 2.7719414234161377
    Affoot: 4.074528694152832
    Afshin: 4.658519268035889
    Afthigh: 2.4508776664733887
    Arooty: 6.048495769500732
    Cbfoot: 2.522000551223755
    Cbshin: 1.8751190900802612
    Cbthigh: 1.352807879447937
    Cffoot: 1.591188907623291
    Cfshin: 1.7662606239318848
    Cfthigh: 1.5853720903396606
    Vrootx: 3.2986342906951904
    Vrootz: 7.118805885314941
    bfoot: 5.3555192947387695
    bshin: 2.886366367340088
    bthigh: 2.5787694454193115
    ffoot: 2.522179126739502
    fshin: 3.9684178829193115
    fthigh: 2.01639461517334
    rooty: 44.587100982666016
    rootz: 20.470108032226562
  names_controls:
  - Cbthigh
  - Cbshin
  - Cbfoot
  - Cfthigh
  - Cfshin
  - Cffoot
  names_positions:
  - rootz
  - rooty
  - bthigh
  - bshin
  - bfoot
  - fthigh
  - fshin
  - ffoot
  names_states:
  - rootz
  - rooty
  - bthigh
  - bshin
  - bfoot
  - fthigh
  - fshin
  - ffoot
  - Vrootx
  - Vrootz
  - Arooty
  - Abthigh
  - Abshin
  - Abfoot
  - Afthigh
  - Afshin
  - Affoot
loss_definitions:
  loss_diffusion:
    cvx_coeff_config:
      cvx_coeff_params:
        coef_init: 100.0
        is_constant: true
      is_cvx_coeff_learned: true
    diff_loss_config:
      ball_num_samples: 20
      ball_radius: 0.1
      cvx_coeff_loss_type: quad_inv
      min_grad_density: 1.0e-06
      weight_diff_loss:
        cvx_coeff_loss: 1
        density_set_one: 0.0001
        density_value: 0.001
        gradient_loss: 1.0e-05
        local_convex_loss: 1
      weight_min_grad_density: 1000.0
  loss_reg:
    default_mean: 0
    default_scale: 0
    specials:
      actuator_forces:
        mean: 0.0
        scale: 1
      coriolis_forces:
        mean: 0.0
        scale: 1
      gravity_forces:
        mean: 0.0
        scale: 1
      position_correction:
        mean: 0.0
        scale: 1
      residual_forces:
        mean: 0.0
        scale: 1
  loss_traj_train:
    discount_factor: 0.9
    likehood:
      discount_factor: 0.9
      nll_type: gauss_approx
      noise_scale:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
    num_substeps: 1
    sampling:
      action_sampling_strategy:
        default: first
      horizon_fit: 1
      integration_method: euler_maruyama
      num_samples: 1
      stepsize_range:
      - 1
      - 1
    validation_sampling:
      action_sampling_strategy:
        default: first
      horizon_test: 5
      stepsize_range:
      - 1
      - 1
  loss_weights:
    DataLoss: 1.0
    RegLoss: 0.0005
    VarBoundLoss: 0.001
model:
  diffusion_term:
    args:
      _num_controls: 6
      _num_states: 17
      default_feature_values: []
      density_free_nn_params:
        activation_fn: swish
        initial_value_range: 0.001
        layers_archictecture: []
      density_nn_params:
        activation_fn: swish
        initial_value_range: 0.1
        layers_archictecture:
        - 64
        - 64
      diffusion_is_control_dependent: true
      feature_density_scaling:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      feature_parameters_to_use: []
      upper_bound_diffusion:
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
    model_name: BasicDistanceAwareDiffusionTerm
  drift_term:
    args:
      _mean_controls:
      - -0.1590409129858017
      - -0.31198182702064514
      - -0.6024095416069031
      - -0.12722280621528625
      - -0.2463710457086563
      - -0.0772140771150589
      _mean_states:
      - -0.05667508766055107
      - 0.02437036857008934
      - -0.06160511076450348
      - -0.22353240847587585
      - -0.26795440912246704
      - -0.07545649260282516
      - -0.05809885635972023
      - -0.027675900608301163
      - 8.110265731811523
      - -0.06136202812194824
      - -0.1798706352710724
      - 0.25175270438194275
      - 0.24186711013317108
      - 0.2519369423389435
      - 0.5879456996917725
      - -0.24090509116649628
      - -0.030184125527739525
      _names_angles:
      - rooty
      - bthigh
      - bshin
      - bfoot
      - fthigh
      - fshin
      - ffoot
      _names_controls:
      - Cbthigh
      - Cbshin
      - Cbfoot
      - Cfthigh
      - Cfshin
      - Cffoot
      _names_positions:
      - rootz
      - rooty
      - bthigh
      - bshin
      - bfoot
      - fthigh
      - fshin
      - ffoot
      _names_states:
      - rootz
      - rooty
      - bthigh
      - bshin
      - bfoot
      - fthigh
      - fshin
      - ffoot
      - Vrootx
      - Vrootz
      - Arooty
      - Abthigh
      - Abshin
      - Abfoot
      - Afthigh
      - Afshin
      - Affoot
      _scale_controls:
      - 0.8567665219306946
      - 0.6996791958808899
      - 0.6353704333305359
      - 0.7110146284103394
      - 0.7056514620780945
      - 0.6769866347312927
      _scale_states:
      - 0.061109114438295364
      - 0.3612094521522522
      - 0.455518513917923
      - 0.3851264715194702
      - 0.22185677289962769
      - 0.5670276284217834
      - 0.3199063241481781
      - 0.2855689823627472
      - 3.4442191123962402
      - 0.6732849478721619
      - 1.8631865978240967
      - 9.5781888961792
      - 10.036422729492188
      - 5.90804386138916
      - 12.138425827026367
      - 6.485083103179932
      - 6.384984493255615
      actuator_forces_nn:
        args:
          activation_fn: swish
          initial_value_range: 0.001
          layers_archictecture:
          - 64
          - 64
          - 64
        features:
        - rootz
        - cos_angles
        - sin_angles
        - velocities
      coriolis_forces_nn:
        args:
          activation_fn: swish
          initial_value_range: 0.001
          layers_archictecture:
          - 64
          - 64
          - 64
        features:
        - rootz
        - cos_angles
        - sin_angles
        - velocities
      gravity_forces_nn: {}
      mass_matrix_nn: {}
      residual_forces_nn:
        args:
          activation_fn: swish
          initial_value_range: 0.001
          layers_archictecture:
          - 200
          - 200
          - 200
        features:
        - rootz
        - cos_angles
        - sin_angles
        - velocities
        - controls
    model_name: RBD_Drift
model_optimizer:
- name: scale_by_adam
- name: linear_schedule
  params:
    end_value: -0.001
    init_value: -0.01
    transition_steps: 100000
  scheduler: true
model_training:
  dad_batch_size: 128
  early_stopping_epochs: 20
  freq_update_dad: 1
  num_gradient_steps: 65
  save_freq: 4000
  test_batch: 128
  test_freq: 2000
  test_num_steps: 80
  train_batch: 128
seed: 50
track_n_checkpoints:
  async_exec: false
  max_to_keep: 5
  metrics:
    Test/StateLoss: 1.0
    Train/TotalLoss: 1.0
    Train/dad_based_diff: 1.0
