dad_optimizer:
- name: scale_by_adam
- name: linear_schedule
  params:
    end_value: -0.001
    init_value: -0.001
    transition_steps: 100000
  scheduler: true
dataset:
  name: walker2d-medium-v2
  normalize_data: true
  seed: 10
  test_ratio: 0.2
env_name: walker2d-medium-v2
extra_infos:
  is_diff_distance_aware: true
  max_fields:
    Abfoot: 2.48256778717041
    Abshin: 3.336940050125122
    Abthigh: 5.535482406616211
    Affoot: 1.8891624212265015
    Afshin: 2.7019283771514893
    Afthigh: 6.851849555969238
    Arooty: 6.4095611572265625
    Cbfoot: 2.0014114379882812
    Cbshin: 2.637089490890503
    Cbthigh: 2.927734613418579
    Cffoot: 1.53592050075531
    Cfshin: 1.9524551630020142
    Cfthigh: 4.778677463531494
    Vrootx: 4.912951946258545
    Vrootz: 5.913363933563232
    bfoot: 3.5135691165924072
    bshin: 9.900039672851562
    bthigh: 12.598231315612793
    ffoot: 2.2102866172790527
    fshin: 5.870439529418945
    fthigh: 8.131979942321777
    rooty: 3.515528678894043
    rootz: 3.4018547534942627
  names_controls:
  - Cbthigh
  - Cbshin
  - Cbfoot
  - Cfthigh
  - Cfshin
  - Cffoot
  names_positions:
  - rootz
  - rooty
  - bthigh
  - bshin
  - bfoot
  - fthigh
  - fshin
  - ffoot
  names_states:
  - rootz
  - rooty
  - bthigh
  - bshin
  - bfoot
  - fthigh
  - fshin
  - ffoot
  - Vrootx
  - Vrootz
  - Arooty
  - Abthigh
  - Abshin
  - Abfoot
  - Afthigh
  - Afshin
  - Affoot
loss_definitions:
  loss_diffusion:
    cvx_coeff_config:
      cvx_coeff_params:
        coef_init: 100.0
        is_constant: true
      is_cvx_coeff_learned: true
    diff_loss_config:
      ball_num_samples: 20
      ball_radius: 0.1
      cvx_coeff_loss_type: quad_inv
      min_grad_density: 1.0e-06
      weight_diff_loss:
        cvx_coeff_loss: 1
        density_set_one: 0.0001
        density_value: 0.001
        gradient_loss: 1.0e-05
        local_convex_loss: 1
      weight_min_grad_density: 1000.0
  loss_reg:
    default_mean: 0
    default_scale: 0
    specials:
      actuator_forces:
        mean: 0.0
        scale: 1
      coriolis_forces:
        mean: 0.0
        scale: 1
      gravity_forces:
        mean: 0.0
        scale: 1
      position_correction:
        mean: 0.0
        scale: 1
      residual_forces:
        mean: 0.0
        scale: 1
  loss_traj_train:
    discount_factor: 0.9
    likehood:
      discount_factor: 0.9
      nll_type: gauss_approx
      noise_scale:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
    num_substeps: 1
    sampling:
      action_sampling_strategy:
        default: first
      horizon_fit: 2
      integration_method: euler_maruyama
      num_samples: 1
      stepsize_range:
      - 1
      - 1
    validation_sampling:
      action_sampling_strategy:
        default: first
      horizon_test: 5
      stepsize_range:
      - 1
      - 1
  loss_weights:
    DataLoss: 1.0
    RegLoss: 0.0005
    VarBoundLoss: 0.001
model:
  diffusion_term:
    args:
      _num_controls: 6
      _num_states: 17
      default_feature_values: []
      density_free_nn_params:
        activation_fn: swish
        initial_value_range: 0.001
        layers_archictecture: []
      density_nn_params:
        activation_fn: swish
        initial_value_range: 0.1
        layers_archictecture:
        - 64
        - 64
      diffusion_is_control_dependent: true
      feature_density_scaling:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      feature_parameters_to_use: []
      upper_bound_diffusion:
      - 0.01
      - 0.01
      - 0.01
      - 0.01
      - 0.01
      - 0.01
      - 0.01
      - 0.01
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
    model_name: BasicDistanceAwareDiffusionTerm
  drift_term:
    args:
      _mean_controls:
      - 0.47035840153694153
      - 0.3588142395019531
      - 0.4219423532485962
      - 0.7531730532646179
      - 0.03651764988899231
      - -0.13054749369621277
      _mean_states:
      - 1.21896231174469
      - 0.14163526892662048
      - -0.03704969212412834
      - -0.13816562294960022
      - 0.5150924921035767
      - -0.04719001054763794
      - -0.4728192389011383
      - 0.0422557108104229
      - 2.3948283195495605
      - -0.03143244981765747
      - 0.04466346278786659
      - -0.023907482624053955
      - -0.10133974999189377
      - 0.09091035276651382
      - -0.004192651249468327
      - -0.12120530009269714
      - -0.5496954321861267
      _names_angles:
      - rooty
      - bthigh
      - bshin
      - bfoot
      - fthigh
      - fshin
      - ffoot
      _names_controls:
      - Cbthigh
      - Cbshin
      - Cbfoot
      - Cfthigh
      - Cfshin
      - Cffoot
      _names_positions:
      - rootz
      - rooty
      - bthigh
      - bshin
      - bfoot
      - fthigh
      - fshin
      - ffoot
      _names_states:
      - rootz
      - rooty
      - bthigh
      - bshin
      - bfoot
      - fthigh
      - fshin
      - ffoot
      - Vrootx
      - Vrootz
      - Arooty
      - Abthigh
      - Abshin
      - Abfoot
      - Afthigh
      - Afshin
      - Affoot
      _scale_controls:
      - 0.5021742582321167
      - 0.5152703523635864
      - 0.7104697227478027
      - 0.3668741285800934
      - 0.5308788418769836
      - 0.7360713481903076
      _scale_states:
      - 0.12314900010824203
      - 0.3243013918399811
      - 0.11457278579473495
      - 0.26230207085609436
      - 0.5641955137252808
      - 0.22723929584026337
      - 0.3838233947753906
      - 0.7373887896537781
      - 1.2390364408493042
      - 0.798317015171051
      - 1.5671374797821045
      - 1.810846209526062
      - 3.0271263122558594
      - 4.064706802368164
      - 1.4600718021392822
      - 3.7459192276000977
      - 5.584323883056641
      actuator_forces_nn:
        args:
          activation_fn: swish
          initial_value_range: 0.001
          layers_archictecture:
          - 128
          - 128
          - 128
        features:
        - rootz
        - cos_angles
        - sin_angles
        - velocities
      coriolis_forces_nn:
        args:
          activation_fn: swish
          initial_value_range: 0.001
          layers_archictecture:
          - 128
          - 128
          - 128
        features:
        - rootz
        - cos_angles
        - sin_angles
        - velocities
      gravity_forces_nn: {}
      mass_matrix_nn: {}
      residual_forces_nn:
        args:
          activation_fn: swish
          initial_value_range: 0.001
          layers_archictecture:
          - 200
          - 200
          - 200
        features:
        - rootz
        - cos_angles
        - sin_angles
        - velocities
        - controls
    model_name: RBD_Drift
model_optimizer:
- name: scale_by_adam
- name: linear_schedule
  params:
    end_value: -0.001
    init_value: -0.01
    transition_steps: 100000
  scheduler: true
model_training:
  dad_batch_size: 128
  early_stopping_epochs: 20
  freq_update_dad: 1
  num_gradient_steps: 65
  save_freq: 4000
  test_batch: 128
  test_freq: 2000
  test_num_steps: 80
  train_batch: 128
seed: 50
track_n_checkpoints:
  async_exec: false
  max_to_keep: 5
  metrics:
    Test/StateLoss: 5.0
    Train/StateLoss: 1.0
