dad_optimizer:
- name: scale_by_adam
- name: linear_schedule
  params:
    end_value: -0.001
    init_value: -0.001
    transition_steps: 100000
  scheduler: true
dataset:
  name: Walker2d-v3-High-1000-neorl
  normalize_data: true
  seed: 10
  test_ratio: 0.2
env_name: Walker2d-v3-High-1000-neorl
extra_infos:
  is_diff_distance_aware: true
  max_fields:
    Abfoot: 1.7536476850509644
    Abshin: 3.10939884185791
    Abthigh: 3.1003365516662598
    Affoot: 2.115874767303467
    Afshin: 2.1501352787017822
    Afthigh: 3.2496769428253174
    Arooty: 3.7299094200134277
    Cbfoot: 7.646749019622803
    Cbshin: 15.850013732910156
    Cbthigh: 11.574033737182617
    Cffoot: 20.567556381225586
    Cfshin: 10.976622581481934
    Cfthigh: 16.337364196777344
    Vrootx: 5.315441608428955
    Vrootz: 7.044388294219971
    bfoot: 2.522827386856079
    bshin: 15.12092399597168
    bthigh: 12.826537132263184
    ffoot: 4.401315689086914
    fshin: 4.678568363189697
    fthigh: 13.28663158416748
    reward: 2.770922181727566
    rootx: 2.946706771850586
    rooty: 7.307410717010498
    rootz: 4.701815128326416
  names_controls:
  - Cbthigh
  - Cbshin
  - Cbfoot
  - Cfthigh
  - Cfshin
  - Cffoot
  names_positions:
  - rootx
  - rootz
  - rooty
  - bthigh
  - bshin
  - bfoot
  - fthigh
  - fshin
  - ffoot
  names_states:
  - rootx
  - rootz
  - rooty
  - bthigh
  - bshin
  - bfoot
  - fthigh
  - fshin
  - ffoot
  - Vrootx
  - Vrootz
  - Arooty
  - Abthigh
  - Abshin
  - Abfoot
  - Afthigh
  - Afshin
  - Affoot
  - reward
loss_definitions:
  loss_diffusion:
    cvx_coeff_config:
      cvx_coeff_params:
        coef_init: 100.0
        is_constant: true
      is_cvx_coeff_learned: true
    diff_loss_config:
      ball_num_samples: 20
      ball_radius: 0.1
      cvx_coeff_loss_type: quad_inv
      min_grad_density: 1.0e-06
      weight_diff_loss:
        cvx_coeff_loss: 1
        density_set_one: 0.0001
        density_value: 0.001
        gradient_loss: 1.0e-05
        local_convex_loss: 1
      weight_min_grad_density: 1000.0
  loss_reg:
    default_mean: 0
    default_scale: 0
    specials:
      actuator_forces:
        mean: 0.0
        scale: 1
      coriolis_forces:
        mean: 0.0
        scale: 1
      gravity_forces:
        mean: 0.0
        scale: 1
      position_correction:
        mean: 0.0
        scale: 1
      residual_forces:
        mean: 0.0
        scale: 1
  loss_traj_train:
    discount_factor: 0.9
    likehood:
      discount_factor: 0.9
      nll_type: gauss_approx
      noise_scale:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
    num_substeps: 1
    sampling:
      action_sampling_strategy:
        default: first
      horizon_fit: 2
      integration_method: euler_maruyama
      num_samples: 1
      stepsize_range:
      - 1
      - 1
    validation_sampling:
      action_sampling_strategy:
        default: first
      horizon_test: 5
      stepsize_range:
      - 1
      - 1
  loss_weights:
    DataLoss: 1.0
    RegLoss: 0.0005
    VarBoundLoss: 0.001
model:
  diffusion_term:
    args:
      _num_controls: 6
      _num_states: 19
      default_feature_values: []
      density_free_nn_params:
        activation_fn: swish
        initial_value_range: 0.001
        layers_archictecture: []
      density_nn_params:
        activation_fn: swish
        initial_value_range: 0.1
        layers_archictecture:
        - 64
        - 64
      diffusion_is_control_dependent: true
      feature_density_scaling:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      feature_parameters_to_use: []
      is_reward_in_state: true
      upper_bound_diffusion:
      - 0.01
      - 0.01
      - 0.01
      - 0.01
      - 0.01
      - 0.01
      - 0.01
      - 0.01
      - 0.01
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0
    model_name: BasicDistanceAwareDiffusionTerm
  drift_term:
    args:
      _mean_controls:
      - 0.3651168644428253
      - 0.3060947358608246
      - -0.03495967388153076
      - 0.4538183808326721
      - 0.07079415768384933
      - -0.4347367286682129
      _mean_states:
      - 7.399054050445557
      - 1.2539821863174438
      - 0.25409063696861267
      - -0.09702662378549576
      - -0.05250387266278267
      - 0.23399285972118378
      - -0.08912889659404755
      - -0.42323940992355347
      - -0.6188980340957642
      - 2.698489189147949
      - -0.06529223173856735
      - 0.05711834877729416
      - -0.10619824379682541
      - -0.10433385521173477
      - -1.1048166751861572
      - -0.04373931139707565
      - -0.201762393116951
      - -0.023803502321243286
      - 1346.20787264997
      _names_angles:
      - rooty
      - bthigh
      - bshin
      - bfoot
      - fthigh
      - fshin
      - ffoot
      _names_controls:
      - Cbthigh
      - Cbshin
      - Cbfoot
      - Cfthigh
      - Cfshin
      - Cffoot
      _names_positions:
      - rootx
      - rootz
      - rooty
      - bthigh
      - bshin
      - bfoot
      - fthigh
      - fshin
      - ffoot
      _names_states:
      - rootx
      - rootz
      - rooty
      - bthigh
      - bshin
      - bfoot
      - fthigh
      - fshin
      - ffoot
      - Vrootx
      - Vrootz
      - Arooty
      - Abthigh
      - Abshin
      - Abfoot
      - Afthigh
      - Afshin
      - Affoot
      - reward
      _scale_controls:
      - 0.7821236848831177
      - 0.6554514765739441
      - 0.7858210206031799
      - 0.6393536329269409
      - 0.6590040922164917
      - 0.6951258778572083
      _scale_states:
      - 5.840012073516846
      - 0.09654933959245682
      - 0.1700696349143982
      - 0.21490564942359924
      - 0.18468545377254486
      - 0.6888251900672913
      - 0.1857510358095169
      - 0.5056537985801697
      - 0.4495915472507477
      - 1.1520514488220215
      - 0.9563261866569519
      - 2.6963438987731934
      - 3.2597100734710693
      - 3.249610185623169
      - 6.3324103355407715
      - 3.090688467025757
      - 4.744707107543945
      - 4.737427711486816
      - 983.2209883286764
      actuator_forces_nn:
        args:
          activation_fn: swish
          initial_value_range: 0.001
          layers_archictecture:
          - 128
          - 128
          - 128
        features:
        - rootz
        - cos_angles
        - sin_angles
        - velocities
      coriolis_forces_nn:
        args:
          activation_fn: swish
          initial_value_range: 0.001
          layers_archictecture:
          - 128
          - 128
          - 128
        features:
        - rootz
        - cos_angles
        - sin_angles
        - velocities
      gravity_forces_nn: {}
      mass_matrix_nn: {}
      residual_forces_nn:
        args:
          activation_fn: swish
          initial_value_range: 0.001
          layers_archictecture:
          - 200
          - 200
          - 200
        features:
        - rootz
        - cos_angles
        - sin_angles
        - velocities
        - controls
      reward_nn:
        args:
          activation_fn: swish
          initial_value_range: 0.001
          layers_archictecture:
          - 64
          - 64
          - 64
        features:
        - positions
        - velocities
        - controls
    model_name: RBD_Drift
model_optimizer:
- name: scale_by_adam
- name: linear_schedule
  params:
    end_value: -0.001
    init_value: -0.01
    transition_steps: 100000
  scheduler: true
model_training:
  dad_batch_size: 128
  early_stopping_epochs: 300
  freq_update_dad: 1
  num_gradient_steps: 400
  save_freq: 4000
  test_batch: 128
  test_freq: 2000
  test_num_steps: 80
  train_batch: 128
seed: 100
track_n_checkpoints:
  async_exec: false
  max_to_keep: 5
  metrics:
    Test/StateLoss: 5.0
    Train/StateLoss: 1.0
