dad_optimizer:
- name: add_decayed_weights
  params:
    weight_decay: 0.0001
- name: scale_by_adam
- name: linear_schedule
  params:
    end_value: -0.001
    init_value: -0.001
    transition_steps: 100000
  scheduler: true
- name: adaptive_grad_clip
  params:
    clipping: 0.01
dataset:
  name: walker2d-random-v2
  normalize_data: true
  seed: 10
  test_ratio: 0.2
env_name: walker2d-random-v2
extra_infos:
  is_diff_distance_aware: true
  max_fields:
    Abfoot: 1.5152980089187622
    Abshin: 2.4704999923706055
    Abthigh: 2.1845104694366455
    Affoot: 1.5108516216278076
    Afshin: 2.464386463165283
    Afthigh: 2.185281753540039
    Arooty: 3.1514511108398438
    Cbfoot: 1.7323455810546875
    Cbshin: 1.7327712774276733
    Cbthigh: 1.733441948890686
    Cffoot: 1.7320588827133179
    Cfshin: 1.7336395978927612
    Cfthigh: 1.735189437866211
    Vrootx: 4.523712158203125
    Vrootz: 5.748837947845459
    bfoot: 3.9358909130096436
    bshin: 5.655369281768799
    bthigh: 4.985406398773193
    ffoot: 4.153099536895752
    fshin: 5.906734466552734
    fthigh: 4.157248020172119
    rooty: 2.1427900791168213
    rootz: 6.722142219543457
  names_controls:
  - Cbthigh
  - Cbshin
  - Cbfoot
  - Cfthigh
  - Cfshin
  - Cffoot
  names_positions:
  - rootz
  - rooty
  - bthigh
  - bshin
  - bfoot
  - fthigh
  - fshin
  - ffoot
  names_states:
  - rootz
  - rooty
  - bthigh
  - bshin
  - bfoot
  - fthigh
  - fshin
  - ffoot
  - Vrootx
  - Vrootz
  - Arooty
  - Abthigh
  - Abshin
  - Abfoot
  - Afthigh
  - Afshin
  - Affoot
loss_definitions:
  loss_diffusion:
    cvx_coeff_config:
      cvx_coeff_params:
        coef_init: 100.0
        is_constant: true
      is_cvx_coeff_learned: true
    diff_loss_config:
      ball_num_samples: 20
      ball_radius: 0.2
      cvx_coeff_loss_type: quad_inv
      min_grad_density: 1.0e-06
      weight_diff_loss:
        cvx_coeff_loss: 1
        density_set_one: 0.0001
        density_value: 0.001
        gradient_loss: 0.0001
        local_convex_loss: 1
      weight_min_grad_density: 1000.0
  loss_reg:
    default_mean: 0
    default_scale: 0
    specials:
      actuator_forces:
        mean: 0.0
        scale: 1
      coriolis_forces:
        mean: 0.0
        scale: 1
      gravity_forces:
        mean: 0.0
        scale: 1
      position_correction:
        mean: 0.0
        scale: 1
      residual_forces:
        mean: 0.0
        scale: 1
  loss_traj_train:
    discount_factor: 0.9
    likehood:
      discount_factor: 0.9
      nll_type: gauss_approx
      noise_scale:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
    num_substeps: 1
    sampling:
      action_sampling_strategy:
        default: first
      horizon: 2
      integration_method: euler_maruyama
      num_samples: 1
      stepsize_range:
      - 1
      - 1
    validation_sampling:
      action_sampling_strategy:
        default: first
      horizon: 5
      stepsize_range:
      - 1
      - 1
  loss_weights:
    DataLoss: 1.0
    RegLoss: 0.0005
    VarBoundLoss: 0.001
model:
  diffusion_term:
    args:
      _num_controls: 6
      _num_states: 17
      default_feature_values: []
      density_free_nn_params:
        activation_fn: swish
        initial_value_range: 0.001
        layers_archictecture: []
      density_nn_params:
        activation_fn: swish
        initial_value_range: 0.1
        layers_archictecture:
        - 64
        - 64
      diffusion_is_control_dependent: true
      feature_density_scaling:
      - 6.722142219543457
      - 2.1427900791168213
      - 4.985406398773193
      - 5.655369281768799
      - 3.9358909130096436
      - 4.157248020172119
      - 5.906734466552734
      - 4.153099536895752
      - 4.523712158203125
      - 5.748837947845459
      - 3.1514511108398438
      - 2.1845104694366455
      - 2.4704999923706055
      - 1.5152980089187622
      - 2.185281753540039
      - 2.464386463165283
      - 1.5108516216278076
      - 1.733441948890686
      - 1.7327712774276733
      - 1.7323455810546875
      - 1.735189437866211
      - 1.7336395978927612
      - 1.7320588827133179
      feature_parameters_to_use: []
      upper_bound_diffusion:
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
    model_name: BasicDistanceAwareDiffusionTerm
  drift_term:
    args:
      _mean_controls:
      - -0.00045926234452053905
      - -0.0006803065189160407
      - -0.0004838071472477168
      - -0.0011540529085323215
      - -0.0011693434789776802
      - 2.2778101993026212e-05
      _mean_states:
      - 1.1991772651672363
      - -0.35098713636398315
      - -0.21853792667388916
      - -0.3024207055568695
      - 0.25761815905570984
      - -0.22020223736763
      - -0.29649820923805237
      - 0.25247156620025635
      - -0.8834772109985352
      - -0.9491214156150818
      - -4.800792217254639
      - -3.068006753921509
      - -3.109922409057617
      - 1.237256646156311
      - -3.0755441188812256
      - -3.070314645767212
      - 1.194701075553894
      _names_angles:
      - rooty
      - bthigh
      - bshin
      - bfoot
      - fthigh
      - fshin
      - ffoot
      _names_controls:
      - Cbthigh
      - Cbshin
      - Cbfoot
      - Cfthigh
      - Cfshin
      - Cffoot
      _names_positions:
      - rootz
      - rooty
      - bthigh
      - bshin
      - bfoot
      - fthigh
      - fshin
      - ffoot
      _names_states:
      - rootz
      - rooty
      - bthigh
      - bshin
      - bfoot
      - fthigh
      - fshin
      - ffoot
      - Vrootx
      - Vrootz
      - Arooty
      - Abthigh
      - Abshin
      - Abfoot
      - Afthigh
      - Afshin
      - Affoot
      _scale_controls:
      - 0.5771514177322388
      - 0.577501118183136
      - 0.5775312781333923
      - 0.5769698023796082
      - 0.5774955749511719
      - 0.5773596167564392
      _scale_states:
      - 0.059374935925006866
      - 0.30288010835647583
      - 0.2790699303150177
      - 0.4235449731349945
      - 0.4045810103416443
      - 0.27968719601631165
      - 0.41915956139564514
      - 0.4078381657600403
      - 0.5837805867195129
      - 0.9857947826385498
      - 4.696500778198242
      - 5.982121467590332
      - 5.306586742401123
      - 7.415872573852539
      - 5.983458995819092
      - 5.3036789894104
      - 7.4095306396484375
      actuator_forces_nn:
        args:
          activation_fn: swish
          initial_value_range: 0.001
          layers_archictecture:
          - 64
          - 64
          - 64
        features:
        - rootz
        - cos_angles
        - sin_angles
        - velocities
      coriolis_forces_nn:
        args:
          activation_fn: swish
          initial_value_range: 0.001
          layers_archictecture:
          - 64
          - 64
          - 64
        features:
        - rootz
        - cos_angles
        - sin_angles
        - velocities
      gravity_forces_nn: {}
      mass_matrix_nn: {}
      residual_forces_nn:
        args:
          activation_fn: swish
          initial_value_range: 0.001
          layers_archictecture:
          - 200
          - 200
          - 200
        features:
        - rootz
        - cos_angles
        - sin_angles
        - velocities
        - controls
    model_name: RBD_Drift
model_optimizer:
- name: scale_by_adam
- name: linear_schedule
  params:
    end_value: -0.001
    init_value: -0.01
    transition_steps: 100000
  scheduler: true
model_training:
  dad_batch_size: 128
  early_stopping_epochs: 5
  freq_update_dad: 1
  num_gradient_steps: 50
  save_freq: 4000
  test_batch: 128
  test_freq: 2000
  test_num_steps: 80
  train_batch: 128
seed: 10
track_n_checkpoints:
  async_exec: false
  max_to_keep: 5
  metrics:
    Test/StateLoss: 1.0
    Train/TotalLoss: 1.0
